export enum PatternType {
  BOX = 'BOX',
  BREAKOUT = 'BREAKOUT',
  BREAKOUT_UP = 'BREAKOUT_UP',
  BREAKOUT_DOWN = 'BREAKOUT_DOWN',
  UPTREND = 'UPTREND',
  DOWNTREND = 'DOWNTREND',
  SUPPORT_RESISTANCE = 'SUPPORT_RESISTANCE',
  TREND_LINE = 'TREND_LINE',
  DOUBLE_TOP = 'DOUBLE_TOP',
  DOUBLE_BOTTOM = 'DOUBLE_BOTTOM',
  HEAD_SHOULDERS = 'HEAD_SHOULDERS',
} 